app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /login
    defaults: { _controller: AppBundle:Auth:login }

logout:
    path: /logout
    defaults: {_controller: AppBundle:Auth:logout }
admin:
    path: /admin

