# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ANONIM: ROLE_ANONIM
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_USER: ROLE_USER
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user: { password:secret,roles:['ROLE_USER']}
                    admin: { password:secret,roles:['ROLE_ADMIN']}
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
        login:
            pattern: ^/login
            security: false
        secured_area:
            pattern: ^/admin
            form_login:
                login_path: _demo_login
                check_path: _security_check
            logout:
                path: _demo_logout

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
