AppBundle\Entity\User:
    type: entity
    table: User
    id:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_user
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    manyToMany:
        roleRole:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: userUser
            joinTable:
                name: user_has_role
                joinColumns:
                    -
                        name: User_id_user
                        referencedColumnName: id_user
                inverseJoinColumns:
                    -
                        name: Role_id_role
                        referencedColumnName: id_role
            orderBy: null
    lifecycleCallbacks: {  }
